name: Hello World Command
on:
  pull_request:
    types:
      - opened
jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        id: check-description
        continue-on-error: true
        #uses: actions/checkout@v1
        uses: nouzbe/check-pull-request-description@v1.11
        

      - name: Create URL to the run output
        if: steps.check-description.outputs.status == 'failure'
        id: vars
        run: echo "bala"
