name: Hello World Command
on:
  pull_request:
    types:
      - opened

jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        id: check-description
        #uses: actions/checkout@v1
        uses: nouzbe/check-pull-request-description@v1.11
        continue-on-error: true
  close:
    runs-on: ubuntu-latest
    steps: 
      - name: Create URL to the run output
        #needs: [helloWorld]
        if: ${{ always() && (needs.helloWorld.result=='failure') }}
        #if: always() && (needs.helloWorld.result == 'failure')
        #if: steps.check-description.outputs.status == 'failure'
        #id: vars
        run: |
          echo "ok"
